apiVersion: v1
kind: Service
metadata:
  name: mock-service
spec:
 type: NodePort
  selector:
    app:  mock-containers
  ports:
    - name: http-port
      protocol: TCP
      port: 8888
      targetPort: 8080
